[package]
name = "mailang-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "WebAssembly bindings for MaìLang"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
mailang-core = { path = "../mailang-core", version = "0.2.5" }
mailang-stdlib = { path = "../mailang-stdlib", version = "0.2.5", features = ["capture-output"] }
wasm-bindgen = "0.2"

[features]
default = ["std"]
std = []
