[package]
name = "mailang-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI for MaìLang"

[[bin]]
name = "mailang"
path = "src/main.rs"

[dependencies]
mailang-core = { path = "../mailang-core", version = "0.2.6" }
mailang-module = { path = "../mailang-module", version = "0.2.6" }
mailang-lsp = { path = "../mailang-lsp", version = "0.2.6" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
