[package]
name = "mailang-vm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Virtual machine for MaìLang"

[dependencies]
mailang-bytecode = { path = "../mailang-bytecode", version = "0.2.5" }
mailang-stdlib = { path = "../mailang-stdlib", version = "0.2.5" }
mailang-gc = { path = "../mailang-gc", version = "0.2.5" }
thiserror = { workspace = true }

[features]
default = ["std", "gc"]
std = ["alloc"]
alloc = []
gc = ["mailang-gc/gc"]
