[package]
name = "mailang-module"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Module loader for MaìLang"

[dependencies]
mailang-ast = { path = "../mailang-ast", version = "0.2.6" }
mailang-parser = { path = "../mailang-parser", version = "0.2.6" }
mailang-compiler = { path = "../mailang-compiler", version = "0.2.6" }
mailang-bytecode = { path = "../mailang-bytecode", version = "0.2.6" }
