[package]
name = "mailang-analyzer"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Semantic analyzer for MaìLang"

[dependencies]
mailang-ast = { path = "../mailang-ast", version = "0.3.1" }
thiserror = { workspace = true }

[dev-dependencies]
mailang-parser = { path = "../mailang-parser", version = "0.3.1" }

[features]
default = []
