[package]
name = "mailang-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Compiler for MaìLang"

[dependencies]
mailang-ast = { path = "../mailang-ast", version = "0.3.0" }
mailang-bytecode = { path = "../mailang-bytecode", version = "0.3.0" }
thiserror = { workspace = true }

[dev-dependencies]
mailang-parser = { path = "../mailang-parser", version = "0.3.0" }
mailang-bytecode = { path = "../mailang-bytecode", version = "0.3.0" }

[features]
default = []
