[package]
name = "mailang-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Compiler for MaìLang"

[dependencies]
mailang-ast = { path = "../mailang-ast" }
mailang-bytecode = { path = "../mailang-bytecode" }
thiserror = { workspace = true }

[features]
default = []
