[package]
name = "mailang-gc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Garbage collector for MaìLang"

[dependencies]
mailang-bytecode = { path = "../mailang-bytecode" }
serde = { workspace = true, optional = true }

[features]
default = ["gc"]
gc = []
alloc = []
